FROM openjdk:17-alpine

MAINTAINER 2024_6SOAT

ARG AWS_ACCESS_KEY
ARG AWS_SECRET_ACCESS

ENV ENV_VAR_FROM_ACTIONS=${AWS_ACCESS_KEY}
ENV ANOTHER_VAR=${AWS_SECRET_ACCESS}

COPY ./target/shogun-lanches-producao-1.jar app.jar

ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["java", "-jar", "/app.jar"]

EXPOSE 8080