apiVersion: v1
kind: ConfigMap
metadata:
  name: app-producao-configmap
data:
  MYSQL_URL: jdbc:mysql://shogun-producao-database.crax9dqhkq1j.us-east-1.rds.amazonaws.com:3306/db_soat_producao?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  URL_PEDIDO: http://a59ebf99a48594bf984f99305ceed3f6-530530245.us-east-1.elb.amazonaws.com