apiVersion: v1
kind: Service
metadata:
  name: app-producao-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30014
  selector:
    app: app-producao-pod