apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-producao-deployment
  labels:
    app: app-producao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-producao-pod
  template:
    metadata:
      labels:
        app: app-producao-pod
    spec:
      serviceAccountName: rds-access-sa
      containers:
        - name: app-container
          image: 6soatgroup74/shogun-lanches-producao:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-producao-configmap
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-producao-opaque
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-producao-opaque
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: actuator/health
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m