apiVersion: v1
kind: Pod
metadata:
  name: app-prodcuao-pod
  labels:
    app: app-producao-pod
spec:
  containers:
    - name: app-producao-container
      image: 6soatgroup74/shogun-lanches-producao:prod
      imagePullPolicy: Always
      ports:
        - containerPort: 8080